export const browserCoreExamples = [
  "mioclaw browser status",
  "mioclaw browser start",
  "mioclaw browser stop",
  "mioclaw browser tabs",
  "mioclaw browser open https://example.com",
  "mioclaw browser focus abcd1234",
  "mioclaw browser close abcd1234",
  "mioclaw browser screenshot",
  "mioclaw browser screenshot --full-page",
  "mioclaw browser screenshot --ref 12",
  "mioclaw browser snapshot",
  "mioclaw browser snapshot --format aria --limit 200",
  "mioclaw browser snapshot --efficient",
  "mioclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "mioclaw browser navigate https://example.com",
  "mioclaw browser resize 1280 720",
  "mioclaw browser click 12 --double",
  'mioclaw browser type 23 "hello" --submit',
  "mioclaw browser press Enter",
  "mioclaw browser hover 44",
  "mioclaw browser drag 10 11",
  "mioclaw browser select 9 OptionA OptionB",
  "mioclaw browser upload /tmp/mioclaw/uploads/file.pdf",
  'mioclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mioclaw browser dialog --accept",
  'mioclaw browser wait --text "Done"',
  "mioclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mioclaw browser console --level error",
  "mioclaw browser pdf",
];
